import { useState } from "react";

function ReportExporter({ report }) {
  const [copied, setCopied] = useState(false);

  if (!report) return null;

  const generateReportText = () => {
    const address = report.address;
    const score = report.score;
    const rating = report.rating;
    const count = report.transaction_count;
    const flags = report.flags ? report.flags.filter((f) => f.detected) : [];

    let text = `=========================================
BITCOIN PRIVACY ANALYSIS REPORT
=========================================
Address: ${address}
Format: ${report.address_info?.format || "N/A"} (${report.address_info?.script_type || "N/A"})
Transactions Analyzed: ${count}
Privacy Score: ${score}/100 (${rating})

SCORE DEDUCTION BREAKDOWN:
--------------------------
`;
    if (report.score_breakdown && report.score_breakdown.length > 0) {
      report.score_breakdown.forEach((b) => {
        text += `- -${b.points} pts (${b.title}): ${b.reason}\n`;
      });
    } else {
      text += `- No deductions. Clean privacy score.\n`;
    }

    text += `\nDETECTED PRIVACY SIGNALS & EVIDENCE:\n-------------------------------------\n`;
    if (flags.length > 0) {
      flags.forEach((f) => {
        text += `• ${f.title} (Severity: ${f.severity.toUpperCase()}, Confidence: ${f.confidence.toUpperCase()})\n`;
        text += `  Message: ${f.message}\n`;
        if (f.why_detected && f.why_detected.length > 0) {
          f.why_detected.forEach((why) => {
            text += `  - Evidence: ${why}\n`;
          });
        }
        if (f.mitigation) {
          text += `  - Mitigation: ${f.mitigation}\n`;
        }
        text += `\n`;
      });
    } else {
      text += `• No configured privacy vulnerability signals detected.\n\n`;
    }

    text += `RECOMMENDED ACTION ITEMS:\n-------------------------\n`;
    if (report.recommendations && report.recommendations.length > 0) {
      report.recommendations.forEach((rec) => {
        text += `[${rec.badge}] ${rec.title}: ${rec.description}\n`;
      });
    }

    text += `\n-----------------------------------------\n`;
    text += `DISCLAIMER: All privacy findings are heuristic indicators based on public blockchain data. They do not prove legal identity or wallet ownership.\n`;
    text += `Generated by Bitcoin Privacy Assistant\n`;

    return text;
  };

  const handleCopy = () => {
    const text = generateReportText();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handleDownload = () => {
    const text = generateReportText();
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `privacy-report-${report.address.slice(0, 8)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="exporter-bar">
      <button className="exporter-btn copy" onClick={handleCopy}>
        {copied ? "✓ Copied to Clipboard!" : "📋 Copy Privacy Report"}
      </button>

      <button className="exporter-btn download" onClick={handleDownload}>
        📥 Download Markdown Report (.md)
      </button>
    </div>
  );
}

export default ReportExporter;
